Repository alkemyTech/OT198-Server, pull requests merged in 2022-05, with the labels that each got.

#12 [ENDPOINT] Get /categories OT198-41
  controllers/categories.js
  routes/categories.js
  routes/index.js
  services/categories.js
Labels: endpoint

#13 [ENDPOINT] - Get /categories/:id Endpoint Detail Category - OT198-42
  controllers/activity.js
  controllers/categories.js
  database/migrations/20220524155902-create-user.js
  database/migrations/20220524285715-create-new.js
  database/models/activity.js
  database/models/category.js
  database/models/new.js
  database/models/role.js
  database/models/user.js
  routes/categories.js
  routes/index.js
  services/categories.js
Labels: endpoint

#15 [ENDPOINT] - Get /news/:id Endpoint Detail New - OT198-46
  controllers/new.js
  controllers/news.js
  routes/index.js
  routes/news.js
  services/news.js
Labels: endpoint

#18 [FIX] OT198-41FIX Fix response message at categories controller
  controllers/categories.js
Labels: fix

#17 [CATEGORY] - Endpoint Creation Categories - OT198-43
  controllers/categories.js
  middlewares/validateErrors.js
  package.json
  routes/categories.js
  schemas/category.js
  services/categories.js
Labels: endpoint

#19 [SLIDES] - Endpoint List Slides - OT198-57
  controllers/slide.js
  routes/index.js
  routes/slide.js
  services/slide.js
Labels: endpoint

#23 [FIX-ENDPOINT] Ot198 57 fix - Get-Slides
  controllers/slide.js
  services/slide.js
Labels: endpoint, fix

#22 [ACTIVITY] ENDPOINT CREATE ACTIVITY OT198-52
  controllers/activity.js
  database/models/activity.js
  routes/activity.js
  routes/index.js
  schemas/activity.js
  services/activity.js
Labels: endpoint

#26 [ ENDPOINT ] OT198-33 Delete User Endpoint
  controllers/user.js
  routes/index.js
  routes/user.js
  services/user.js
Labels: endpoint

#31 [ENDPOINT] - DELETE /categories/:id - OT198-45
  controllers/categories.js
  routes/categories.js
  services/categories.js
Labels: endpoint

#30 [MIDDLEWARE] Ot198 26 - Middleware for Authenticated Users
  config/auth.js
  middlewares/auth.js
  middlewares/jwt.js
  package.json
  routes/index.js
Labels: middleware

#33 [MIDDLEWARE] OT198-27 Middleware for Admin users
  middlewares/isAdmin.js
Labels: middleware

#39 [ENDPOINT] UPDATE CATEGORIES OT-198-44
  controllers/categories.js
  routes/categories.js
  services/categories.js
Labels: endpoint

#40 [ENDPOINT] OT198-36 Endpoint user get
  controllers/user.js
  routes/user.js
  services/user.js
Labels: endpoint

#44 [ENDPOINT] OT198-38 Update organization public data
  controllers/organization.js
  routes/organization.js
  schemas/organization.js
  services/organization.js
Labels: endpoint

#46 [ FIX ] OT198-30-FIX Add properties at welcomeEmail template
  services/sendgrid.js
  templates/welcomeEmail.js
Labels: fix
