Repository alkemyTech/OT198-Server, pull requests merged in 2022-06, with the labels that each got.

#45 [ENDPOINT] OT198-48 Create Endpoint Update News
  controllers/news.js
  routes/news.js
  services/news.js
Labels: endpoint

#52 [ENDPOINT] - Create Testimonial - OT198-69
  controllers/testimonial.js
  routes/index.js
  routes/testimonial.js
  schemas/testimonial.js
  services/testimonial.js
Labels: endpoint

#51 [ENDPOINT] - Delete A New - OT198-50
  controllers/news.js
  routes/news.js
  services/news.js
Labels: endpoint

#62 [ENDPOINT] OT198-56 Create Endpoint post contacts
  controllers/contacts.js
  helpers/ApiError.js
  routes/contacts.js
  schemas/contact.js
  services/contacts.js
Labels: endpoint

#63 Upload Images OT198-40
  libs/s3Client.js
  middlewares/uploadImage.js
  middlewares/validateErrors.js
  package.json
  services/uploadImageToS3.js
Labels: middleware

#64 [ENDPOINT] - Slides update route, controller and service and schema - OT198-60
  controllers/slide.js
  routes/slide.js
  schemas/slide.js
  services/slide.js
Labels: endpoint

#65 [ERRORHANDLER] - Add node env develoment to show more errors when dev
  middlewares/errorHandler.js
Labels: enhancement

#60 [ ENDPOINT ] OT198-53 Endpoint Update Activities
  controllers/activity.js
  routes/activity.js
  services/activity.js
Labels: endpoint

#69 [ENDPOINT] - Delete Testimonial endpoint - OT198-71
  controllers/testimonial.js
  routes/testimonial.js
  services/testimonial.js
Labels: endpoint

#71 [ENDPOINT] - Update testimonial - OT198-70
  controllers/testimonial.js
  routes/testimonial.js
  schemas/testimonial.js
  services/testimonial.js
Labels: endpoint

#76 [ ENDPOINT ] OT198-61 Delete Slide Endpoint
  controllers/slide.js
  routes/slide.js
  services/slide.js
Labels: endpoint

#82 [ENDPOINT] Create Endpoint post Members
  controllers/members.js
  routes/index.js
  routes/members.js
  schemas/member.js
  services/members.js
Labels: endpoint

#80 [ENDPOINT] OT198-73 get Members, create routes, service, and refactor controller
  controllers/members.js
  routes/members.js
  services/members.js
Labels: endpoint

#91 [ENDPOINT] - Endpoint api/docs - Swagger - OT198-89
  package.json
  routes/index.js
  routes/swagger.js
  swagger/basicInfo.js
  swagger/index.js
  swagger/server.js
Labels: endpoint

#87 [ ENDPOINT ] OT198-81 Create Comments Endpoint
  controllers/comments.js
  routes/comments.js
  schemas/comment.js
  services/comments.js
Labels: endpoint

#94 Normalization of controllers and services OT109-Normalization
  controllers/activity.js
  controllers/categories.js
  controllers/comments.js
  controllers/contacts.js
  controllers/members.js
  controllers/news.js
  controllers/organization.js
  controllers/role.js
  controllers/slide.js
  controllers/testimonial.js
  controllers/user.js
  routes/news.js
  routes/organization.js
  services/activity.js
  services/categories.js
  services/comments.js
  services/contacts.js
  services/news.js
  services/organization.js
  services/role.js
  services/slide.js
  services/user.js
Labels: fix

#97 [ ENDPOINT ]OT198-76 Update Members Endpoint
  controllers/members.js
  routes/members.js
  schemas/member.js
  services/members.js
Labels: endpoint

#104 [ FIX ] OT198-FIX-USER Create Roles Constant
  constants/roles.js
  database/seeders/20220607144743-users.js
  middlewares/isAdmin.js
  middlewares/ownership.js
  services/comments.js
  services/user.js
Labels: fix

#105 [ FIX ] OT198-FIX-OWNERSHIP Fix Ownership Middleware
  middlewares/ownership.js
  routes/comments.js
  services/comments.js
Labels: fix

#107 [SWAGGER] OT198-90 Add Documentation to Categories
  routes/categories.js
Labels: documentation

#111 [ SWAGGER ] Add Member Documentation
  routes/members.js
Labels: documentation

#112 [ TEST ] OT198-101 Test: Endpoints /authentication
  test/auth.test.js
Labels: test

#113 [ FIX ] OT198-FIX-ROUTES Code refactor when import schemas
  controllers/news.js
  routes/categories.js
  routes/news.js
Labels: fix

#114 [ FIX ] OT198-FIX-NEWS Add uploadImage in News
  controllers/news.js
  routes/news.js
  services/news.js
Labels: fix

#120 [ TEST ] OT198-101-FIX Add Test Route GET /auth/me
  test/auth.test.js
Labels: fix, test
